mu: 0.1
voxel_size: 0.1
training_data: 'nyu_cad'
batch_name: 'nyu_cad'

pca:
    number_points_from_each_image: 100
    number_dims: 400

    # max number of examples to use for pca
    subsample_length: 10000

    # use fewer sequences for pca then for the main training, for memory reasons
    # however, should ensure these are taken evenly through the training set
    # in case there is inherent ordering to the training data
    max_sequences: 150

number_points_from_each_image: 500

# which features to use, can be 'samples' or 'cobweb'
# features: ['cobweb', 'samples']

# distance between points on the cobweb feature
cobweb_offset: 0.01
cobweb_use_mask: False

# voxel sampling features
vox_num_rings: 10
vox_radius: 0.035
samples_out_of_range_feature: -0.1
idxs_out_of_range_feature: 0.0

# sampling_grid_size: 0.1
ml_type: 'forest'

# do we presegment?
segment_scene: False
segment_with_gt: False


# if a feature is out of the inlier mask, give it this value
cobweb_out_of_range_feature: -5.0

extract_from: 'actual_tsdf'

forest: &DEFAULT_FOREST
    num_tests: 4000
    min_sample_cnt: 5
    max_depth: 30
    num_trees: 40
    bag_size: 0.5
    train_parallel: True
    njobs: 3

    # structured learning params
    #pca_dims: 5
    num_dims_for_pca: 100 # number of dimensions that pca gets reduced to
    sub_sample_exs_pca: True  # can also subsample the number of exs we use for PCA
    num_exs_for_pca: 5000

    oob_score: True
    oob_importance: False

    my_bagging: False

    subsample_length: 100000

# setting some voxlet params here
# NOTE BE VERY CAREFUL IF EDITING THESE
# NOTE SERIOUSLY
# NOTE SERIOUSLY PLEASE YOU SCREW THIS UP EVERY TIME
voxlet_sizes:
    short_0.02:
        name: 'short_0.02'
        tall_voxlets: False
        one_side_bins: 20
        shape: [20, 40, 20]
          # edge size of a single voxel
        size: 0.02
        # centre is relative to the ijk origin at the bottom corner of the voxlet
        # z height of centre takes into account the origin offset
        relative_centre: [0.5, 0.25, 0.5]

    tall_0.02:
        name: 'tall_0.02'
        tall_voxlets: True
        one_side_bins: 20
        shape: [20, 40, 50]
          # edge size of a single voxel
        size: 0.02
        # centre is relative to the ijk origin at the bottom corner of the voxlet
        # z height of centre takes into account the origin offset
        relative_centre: [0.5, 0.25]
        tall_voxlet_height: 0.5

    #
    # short_0.01:
    #     name: 'short_0.01'
    #     tall_voxlets: False
    #     one_side_bins: 20
    #     shape: [20, 40, 20]
    #     size: 0.01
    #     relative_centre: [0.5, 0.25, 0.5]
    #
    # short_0.02:
    #     name: 'short_0.02'
    #     tall_voxlets: False
    #     one_side_bins: 20
    #     shape: [20, 40, 20]
    #     size: 0.02
    #     relative_centre: [0.5, 0.25, 0.5]
    # #
    # short_0.025:
    #     name: 'short_0.025'
    #     tall_voxlets: False
    #     one_side_bins: 20
    #     shape: [20, 40, 20]
    #     size: 0.025
    #     relative_centre: [0.5, 0.25, 0.5]
    #
    # short_0.03:
    #     name: 'short_0.03'
    #     tall_voxlets: False
    #     one_side_bins: 20
    #     shape: [20, 40, 20]
    #     size: 0.03
    #     relative_centre: [0.5, 0.25, 0.5]
    #
    # short_0.04:
    #     name: 'short_0.04'
    #     tall_voxlets: False
    #     one_side_bins: 20
    #     shape: [20, 40, 20]
    #     size: 0.04
    #     relative_centre: [0.5, 0.25, 0.5]


models_to_train:

# -   name: 'short_cobweb_syn'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     forest:
#         <<: *DEFAULT_FOREST
#
# -   name: 'tall_cobweb'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     forest:
#         <<: *DEFAULT_FOREST
#
# -   name: 'short_cobweb'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     forest:
#         <<: *DEFAULT_FOREST

# -   name: 'tall_samples'
#     voxlet_type: 'tall'
#     feature: 'samples'
#     forest:
#         <<: *DEFAULT_FOREST


#
# -   name: 'short_samples'
#     voxlet_type: 'short'
#     feature: 'samples'
#     forest:
#         <<: *DEFAULT_FOREST

# -   name: 'short_samples'
#     voxlet_type: 'short'
#     feature: 'samples'
#     forest:
#         <<: *DEFAULT_FOREST
#
# -   name: 'tall_samples'
#     voxlet_type: 'tall'
#     feature: 'samples'
#     forest:
#         <<: *DEFAULT_FOREST
#
# -   name: 'short_samples_0.01'
#     voxlet_type: 'short_0.01'
#     feature: 'samples'
#     forest:
#         <<: *DEFAULT_FOREST

-   name: 'short_samples_0.02'
    voxlet_type: 'short_0.02'
    feature: 'samples'
    forest:
        <<: *DEFAULT_FOREST
#
-   name: 'tall_samples_0.02'
    voxlet_type: 'tall_0.02'
    feature: 'samples'
    forest:
        <<: *DEFAULT_FOREST
#
# -   name: 'short_samples_0.025'
#     voxlet_type: 'short_0.025'
#     feature: 'samples'
#     forest:
#         <<: *DEFAULT_FOREST
#
# -   name: 'short_samples_0.03'
#     voxlet_type: 'short_0.03'
#     feature: 'samples'
#     forest:
#         <<: *DEFAULT_FOREST
#
# -   name: 'short_samples_0.04'
#     voxlet_type: 'short_0.04'
#     feature: 'samples'
#     forest:
#         <<: *DEFAULT_FOREST
#



# -   name: 'short_cobweb_005_scenes'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     num_scenes: 5
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_010_scenes'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     num_scenes: 10
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'tall_cobweb_005_scenes'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     num_scenes: 5
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'tall_cobweb_010_scenes'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     num_scenes: 10
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST



# -   name: 'short_cobweb_300_scenes'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     num_scenes: 300
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_150_scenes'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     num_scenes: 150
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_075_scenes'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     num_scenes: 75
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_050_scenes'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     num_scenes: 50
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_025_scenes'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     num_scenes: 25
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'tall_cobweb_300_scenes'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     num_scenes: 300
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'tall_cobweb_150_scenes'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     num_scenes: 150
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'tall_cobweb_075_scenes'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     num_scenes: 75
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'tall_cobweb_050_scenes'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     num_scenes: 50
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'tall_cobweb_025_scenes'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     num_scenes: 25
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_0.005'
#     voxlet_type: 'short_0.005'
#     feature: 'cobweb'
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_0.0125'
#     voxlet_type: 'short_0.0125'
#     feature: 'cobweb'
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_0.00125'
#     voxlet_type: 'short_0.00125'
#     feature: 'cobweb'
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_0.002'
#     voxlet_type: 'short_0.002'
#     feature: 'cobweb'
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_0.004'
#     voxlet_type: 'short_0.004'
#     feature: 'cobweb'
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_0.0025'
#     voxlet_type: 'short_0.0025'
#     feature: 'cobweb'
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_0.01'
#     voxlet_type: 'short_0.01'
#     feature: 'cobweb'
#     forest:
#         num_trees:
#         <<: *DEFAULT_FOREST






# -   name: 'tall_cobweb_100_trees'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     forest:
#         num_trees: 100
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     forest:
#         <<: *DEFAULT_FOREST

# -   name: 'tall_cobweb'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     forest:
#         <<: *DEFAULT_FOREST

# -   name: 'short_cobweb_no_bag'
#     voxlet_type: 'short'
#     feature: 'cobweb'
#     forest:
#         my_bagging: False
#         <<: *DEFAULT_FOREST

# -   name: 'tall_cobweb_no_bag'
#     voxlet_type: 'tall'
#     feature: 'cobweb'
#     forest:
#         my_bagging: False
#         <<: *DEFAULT_FOREST



# max num examples to use to train forest
# 50000
# 250000
