mu: 0.025
voxel_size: 0.005

max_sequences: 500
cores: 8
pca_number_points_from_each_image: 250

# setting some voxlet params here
# NOTE BE VERY CAREFUL IF EDITING THESE
voxlets:
    -   name: 'short'
        tall_voxlets: False
        one_side_bins: 20
        shape: [20, 40, 20]
          # edge size of a single voxel
        size: 0.0075
        # centre is relative to the ijk origin at the bottom corner of the voxlet
        # z height of centre takes into account the origin offset
        relative_centre: [0.5, 0.25, 0.5]

    -   name: 'tall'
        tall_voxlets: True
        one_side_bins: 20
        shape: [20, 40, 50]
          # edge size of a single voxel
        size: 0.0075
        # centre is relative to the ijk origin at the bottom corner of the voxlet
        # z height of centre takes into account the origin offset
        relative_centre: [0.5, 0.25, 0.5]

pca_number_points_from_each_image: 200
number_pca_dims: 400

# max number of examples to use for pca
pca_subsample_length: 10000

number_points_from_each_image: 1500

# max num examples to use to train forest
forest_subsample_length: 500000

# number of points to sample from image at test time
number_samples: 300

# sampling_grid_size = 0.1