# config file for the models
---
-   name:               patch_and_spider_5k_10trees
    number_samples:     5000
    features:           [patch_features, spider_features]
    trees:              10

-   name:               patch_250k_10trees
    number_samples:     250000
    features:           [patch_features]
    trees:              10

-   name:               patch_and_spider_250k_10trees
    number_samples:     250000
    features:           [patch_features, spider_features]
    trees:              10

-   name:               spider_250k_10trees
    number_samples:     250000
    features:           [spider_features]
    trees:              10

-   name:               patch_5k_10trees
    number_samples:     5000
    features:           [patch_features]
    trees:              10
